class_name Elements
extends RefCounted

# Tunable game values, not a physical chemistry model.
# Mass affects flow resistance and weight; gravity affects flight, flow and weight.
# grain_size sets disc diameter and area; repose_slope is the retained slope.
# flow_rate sets mobility; damping and surface_friction resist surface flow.
# impact_spread controls the arrival fan and deposition footprint.
# impact_settle_seconds eases the incoming load; capped at 35% of flight.
# Compaction is an instantaneous, reversible pressure equilibrium.  The three
# pressure/packing stages describe loose material through to a dense interior.
# `compaction_response` scales how readily a profile reaches those stages;
# `compaction_creep` keeps a small yielded contact open for rough materials.
# The legacy circle solver uses these values differently; see docs/SURFACE.md.
const HYDROGEN := {
	"id": "H",
	"name": "Hydrogen",
	"color": Color("f6b85f"),
	"mass": 1.0,
	"grain_size": 2.0,
	"gravity_response": 1.0,
	"repose_slope": 0.0, # Hydrogen has no yield slope: it pools like a fluid.
	"surface_friction": 0.04,
	"flow_rate": 1800.0,
	"damping": 0.18,
	"impact_spread": 1.0,
	"impact_settle_seconds": 0.55,
	"compaction_loose_packing": 0.72,
	"compaction_stage_pressures": Vector3(180.0, 950.0, 4500.0),
	"compaction_stage_packings": Vector3(0.79, 0.87, 0.94),
	"core_layer_min_grains": 250000,
	"core_layer_grains": 100000,
	"core_layer_min_packing": 0.45,
	"core_layer_area_ratio": 0.10,
	"core_layer_duration": 1.4,
	"body_kind": "Planet",
	"surface_kind": "Crust",
	"inner_layer_min_mass": 200000.0,
	"inner_layer_mass_fraction": 0.90,
	"inner_layer_area_ratio": 0.10,
	"inner_layer_duration": 1.4,
	"inner_automation_multiplier": 1.75,
	"inner_mantle_fraction": 0.60,
	"outer_mantle_fraction": 0.35,
	"surface_fraction": 0.05,
	"compaction_response": 1.0,
	"compaction_creep": 0.08,
	"compaction_depth_darkening": 0.20,
	"cells": [Vector2i.ZERO]
}

# Later elements are available through the developer selector.
const HELIUM := {
	"id": "He",
	"name": "Helium",
	"color": Color("ffe2a8"),
	"mass": 2.0,
	"grain_size": 2.5,
	"gravity_response": 1.0,
	"repose_slope": 0.18,
	"surface_friction": 0.12,
	"flow_rate": 1200.0,
	"damping": 0.22,
	"impact_spread": 0.8,
	"impact_settle_seconds": 0.50,
	"compaction_loose_packing": 0.73,
	"compaction_stage_pressures": Vector3(110.0, 650.0, 3000.0),
	"compaction_stage_packings": Vector3(0.81, 0.90, 0.955),
	"core_layer_min_grains": 250000,
	"core_layer_grains": 100000,
	"core_layer_min_packing": 0.45,
	"core_layer_area_ratio": 0.10,
	"core_layer_duration": 1.4,
	"body_kind": "Planet",
	"surface_kind": "Crust",
	"inner_layer_min_mass": 200000.0,
	"inner_layer_mass_fraction": 0.90,
	"inner_layer_area_ratio": 0.10,
	"inner_layer_duration": 1.4,
	"inner_automation_multiplier": 1.75,
	"inner_mantle_fraction": 0.60,
	"outer_mantle_fraction": 0.35,
	"surface_fraction": 0.05,
	"compaction_response": 1.08,
	"compaction_creep": 0.06,
	"compaction_depth_darkening": 0.23,
	"cells": [Vector2i.ZERO, Vector2i(1, 0)]
}
const CARBON := {
	"id": "C",
	"name": "Carbon",
	"color": Color("7b8998"),
	"mass": 6.0,
	"grain_size": 4.0,
	"gravity_response": 1.0,
	"repose_slope": 0.7,
	"surface_friction": 0.65,
	"flow_rate": 300.0,
	"damping": 0.28,
	"impact_spread": 0.25,
	"impact_settle_seconds": 0.40,
	"compaction_loose_packing": 0.76,
	"compaction_stage_pressures": Vector3(80.0, 450.0, 2200.0),
	"compaction_stage_packings": Vector3(0.85, 0.93, 0.975),
	"core_layer_min_grains": 250000,
	"core_layer_grains": 100000,
	"core_layer_min_packing": 0.45,
	"core_layer_area_ratio": 0.10,
	"core_layer_duration": 1.4,
	"body_kind": "Planet",
	"surface_kind": "Crust",
	"inner_layer_min_mass": 200000.0,
	"inner_layer_mass_fraction": 0.90,
	"inner_layer_area_ratio": 0.10,
	"inner_layer_duration": 1.4,
	"inner_automation_multiplier": 1.75,
	"inner_mantle_fraction": 0.60,
	"outer_mantle_fraction": 0.35,
	"surface_fraction": 0.05,
	"compaction_response": 1.15,
	"compaction_creep": 0.035,
	"compaction_depth_darkening": 0.27,
	"cells": [Vector2i.ZERO, Vector2i(1, 0), Vector2i(0, 1), Vector2i(1, 1)]
}
const IRON := {
	"id": "Fe",
	"name": "Iron",
	"color": Color("b6a1a0"),
	"mass": 14.0,
	"grain_size": 5.0,
	"gravity_response": 1.0,
	"repose_slope": 1.2,
	"surface_friction": 0.82,
	"flow_rate": 120.0,
	"damping": 0.32,
	"impact_spread": 0.1,
	"impact_settle_seconds": 0.35,
	"compaction_loose_packing": 0.80,
	"compaction_stage_pressures": Vector3(60.0, 350.0, 1600.0),
	"compaction_stage_packings": Vector3(0.90, 0.96, 0.99),
	"core_layer_min_grains": 250000,
	"core_layer_grains": 100000,
	"core_layer_min_packing": 0.45,
	"core_layer_area_ratio": 0.10,
	"core_layer_duration": 1.4,
	"body_kind": "Planet",
	"surface_kind": "Crust",
	"inner_layer_min_mass": 200000.0,
	"inner_layer_mass_fraction": 0.90,
	"inner_layer_area_ratio": 0.10,
	"inner_layer_duration": 1.4,
	"inner_automation_multiplier": 1.75,
	"inner_mantle_fraction": 0.60,
	"outer_mantle_fraction": 0.35,
	"surface_fraction": 0.05,
	"compaction_response": 1.22,
	"compaction_creep": 0.02,
	"compaction_depth_darkening": 0.30,
	"cells": [Vector2i.ZERO, Vector2i(1, 0), Vector2i(0, 1), Vector2i(1, 1), Vector2i(2, 0), Vector2i(2, 1)]
}
